-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["furniture_tables_high_01_24"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_16", "desks_01_18", "desks_01_24", "desks_01_26", "desks_01_20", "desks_01_28", "desks_01_22", "desks_01_30"} }}
overlayMap["furniture_tables_high_01_25"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_17", "desks_01_25", "desks_01_19", "desks_01_27", "desks_01_21", "desks_01_29", "desks_01_23", "desks_01_31"} }}
overlayMap["furniture_tables_high_01_26"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_0", "desks_01_2", "desks_01_4", "desks_01_6", "desks_01_14", "desks_01_12", "desks_01_10", "desks_01_8"} }}
overlayMap["furniture_tables_high_01_27"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_1", "desks_01_9", "desks_01_11", "desks_01_3", "desks_01_5", "desks_01_13", "desks_01_7", "desks_01_15"} }}
overlayMap["furniture_tables_high_01_28"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_56", "desks_01_48", "desks_01_50", "desks_01_58", "desks_01_52", "desks_01_60", "desks_01_54", "desks_01_62"} }}
overlayMap["furniture_tables_high_01_29"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_49", "desks_01_57", "desks_01_59", "desks_01_51", "desks_01_53", "desks_01_61", "desks_01_55", "desks_01_63"} }}
overlayMap["furniture_tables_high_01_30"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_32", "desks_01_40", "desks_01_42", "desks_01_34", "desks_01_36", "desks_01_44", "desks_01_46", "desks_01_38"} }}
overlayMap["furniture_tables_high_01_31"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_33", "desks_01_41", "desks_01_43", "desks_01_35", "desks_01_37", "desks_01_45", "desks_01_47", "desks_01_39"} }}
overlayMap["location_business_office_generic_01_0"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_16", "desks_01_24", "desks_01_18", "desks_01_26", "desks_01_20", "desks_01_28", "desks_01_22", "desks_01_30"} }}
overlayMap["location_business_office_generic_01_1"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_17", "desks_01_25", "desks_01_27", "desks_01_19", "desks_01_21", "desks_01_29", "desks_01_23", "desks_01_31"} }}
overlayMap["location_business_office_generic_01_5"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_0", "desks_01_2", "desks_01_4", "desks_01_6", "desks_01_14", "desks_01_12", "desks_01_10", "desks_01_8"} }}
overlayMap["location_business_office_generic_01_6"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_1", "desks_01_9", "desks_01_3", "desks_01_11", "desks_01_5", "desks_01_13", "desks_01_7", "desks_01_15"} }}
overlayMap["location_business_office_generic_01_8"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_32", "desks_01_34", "desks_01_36", "desks_01_38", "desks_01_46", "desks_01_44", "desks_01_42", "desks_01_40"} }}
overlayMap["location_business_office_generic_01_10"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_33", "desks_01_35", "desks_01_37", "desks_01_39", "desks_01_47", "desks_01_45", "desks_01_43", "desks_01_41"} }}
overlayMap["location_business_office_generic_01_13"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_48", "desks_01_50", "desks_01_52", "desks_01_54", "desks_01_62", "desks_01_60", "desks_01_58", "desks_01_56"} }}
overlayMap["location_business_office_generic_01_14"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_49", "desks_01_57", "desks_01_59", "desks_01_51", "desks_01_53", "desks_01_61", "desks_01_63", "desks_01_55"} }}
overlayMap["location_business_office_generic_01_16"] = {{ name = "other", chance = 4, usage = "", tiles = {"office_01_0", "office_01_1"} }}
overlayMap["location_business_office_generic_01_17"] = {{ name = "other", chance = 4, usage = "", tiles = {"office_01_2", "office_01_3"} }}
overlayMap["location_business_office_generic_01_18"] = {{ name = "other", chance = 6, usage = "", tiles = {"office_01_16", "office_01_17", "office_01_18", "office_01_19"} }}
overlayMap["location_business_office_generic_01_19"] = {{ name = "other", chance = 6, usage = "", tiles = {"office_01_20", "office_01_21", "office_01_22", "office_01_23"} }}
overlayMap["location_business_office_generic_01_21"] = {{ name = "other", chance = 6, usage = "", tiles = {"office_01_16", "office_01_17", "office_01_18", "office_01_19"} }}
overlayMap["location_business_office_generic_01_22"] = {{ name = "other", chance = 6, usage = "", tiles = {"office_01_20", "office_01_21", "office_01_22", "office_01_23"} }}
overlayMap["location_business_office_generic_01_24"] = {{ name = "other", chance = 4, usage = "", tiles = {"office_01_8", "office_01_9"} }}
overlayMap["location_business_office_generic_01_25"] = {{ name = "other", chance = 4, usage = "", tiles = {"office_01_10", "office_01_11"} }}
overlayMap["location_business_office_generic_01_26"] = {{ name = "other", chance = 6, usage = "", tiles = {"office_01_24", "office_01_25", "office_01_26", "office_01_27"} }}
overlayMap["location_business_office_generic_01_27"] = {{ name = "other", chance = 6, usage = "", tiles = {"office_01_28", "office_01_29", "office_01_30", "office_01_31"} }}
overlayMap["location_business_office_generic_01_29"] = {{ name = "other", chance = 6, usage = "", tiles = {"office_01_24", "office_01_25", "office_01_26", "office_01_27"} }}
overlayMap["location_business_office_generic_01_30"] = {{ name = "other", chance = 6, usage = "", tiles = {"office_01_28", "office_01_29", "office_01_30", "office_01_31"} }}
overlayMap["location_business_office_generic_01_32"] = {{ name = "other", chance = 4, usage = "", tiles = {"office_01_4", "office_01_5"} }}
overlayMap["location_business_office_generic_01_33"] = {{ name = "other", chance = 4, usage = "", tiles = {"office_01_6", "office_01_7"} }}
overlayMap["location_business_office_generic_01_34"] = {{ name = "other", chance = 4, usage = "", tiles = {"office_01_12", "office_01_13"} }}
overlayMap["location_business_office_generic_01_35"] = {{ name = "other", chance = 4, usage = "", tiles = {"office_01_14", "office_01_15"} }}
overlayMap["location_business_office_generic_01_40"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_16", "desks_01_18", "desks_01_20", "desks_01_22", "desks_01_24", "desks_01_26", "desks_01_28", "desks_01_30"} }}
overlayMap["location_business_office_generic_01_41"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_17", "desks_01_25", "desks_01_19", "desks_01_27", "desks_01_21", "desks_01_29", "desks_01_23", "desks_01_31"} }}
overlayMap["location_business_office_generic_01_42"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_0", "desks_01_2", "desks_01_4", "desks_01_6", "desks_01_14", "desks_01_12", "desks_01_10", "desks_01_8"} }}
overlayMap["location_business_office_generic_01_43"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_1", "desks_01_9", "desks_01_11", "desks_01_3", "desks_01_5", "desks_01_13", "desks_01_15", "desks_01_7"} }}
overlayMap["location_business_office_generic_01_44"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_32", "desks_01_40", "desks_01_34", "desks_01_42", "desks_01_36", "desks_01_44", "desks_01_38", "desks_01_46"} }}
overlayMap["location_business_office_generic_01_45"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_33", "desks_01_41", "desks_01_43", "desks_01_35", "desks_01_37", "desks_01_45", "desks_01_47", "desks_01_39"} }}
overlayMap["location_business_office_generic_01_46"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_48", "desks_01_50", "desks_01_52", "desks_01_54", "desks_01_62", "desks_01_60", "desks_01_58", "desks_01_56"} }}
overlayMap["location_business_office_generic_01_47"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_49", "desks_01_57", "desks_01_59", "desks_01_51", "desks_01_53", "desks_01_61", "desks_01_63", "desks_01_55"} }}
overlayMap["location_community_school_01_4"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_64", "desks_01_65", "desks_01_66", "desks_01_67", "desks_01_72", "desks_01_73", "desks_01_74", "desks_01_75"} }}
overlayMap["location_community_school_01_5"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_68", "desks_01_69", "desks_01_70", "desks_01_71", "desks_01_76", "desks_01_77", "desks_01_78", "desks_01_79"} }}
overlayMap["location_community_school_01_6"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_80", "desks_01_81", "desks_01_82", "desks_01_83", "desks_01_88", "desks_01_89", "desks_01_90", "desks_01_91"} }}
overlayMap["location_community_school_01_7"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_84", "desks_01_85", "desks_01_86", "desks_01_87", "desks_01_92", "desks_01_93", "desks_01_94", "desks_01_95"} }}
overlayMap["location_community_school_01_12"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_64", "desks_01_65", "desks_01_66", "desks_01_67", "desks_01_72", "desks_01_73", "desks_01_74", "desks_01_75"} }}
overlayMap["location_community_school_01_13"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_68", "desks_01_69", "desks_01_70", "desks_01_71", "desks_01_76", "desks_01_77", "desks_01_78", "desks_01_79"} }}
overlayMap["location_community_school_01_14"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_80", "desks_01_81", "desks_01_82", "desks_01_83", "desks_01_88", "desks_01_89", "desks_01_90", "desks_01_91"} }}
overlayMap["location_community_school_01_15"] = {{ name = "other", chance = 8, usage = "tabletop", tiles = {"desks_01_84", "desks_01_85", "desks_01_86", "desks_01_87", "desks_01_92", "desks_01_93", "desks_01_94", "desks_01_95"} }}

if not TILEZED then
	getTileOverlays():addOverlays(overlayMap)
end

return overlayMap
