return {
    VERSION = 4,
    Speed = 3,
    Zombies = 3,
    Distribution = 1,
    Survivors = 1,

    DayLength = 3,
    StartYear = 1,
    StartMonth = 7,
    StartDay = 9,
    StartTime = 2,

	-- the number of day before water shut off (-1 mean instant)
    WaterShutModifier = 14,
	-- the number of day before elec shut off (-1 mean instant)
    ElecShutModifier = 14,
	WaterShut = 2,
	ElecShut = 2,
    FoodLoot = 2,
    WeaponLoot = 2,
    OtherLoot = 2,
	Temperature = 3,
	Rain = 3,
--	Erosion = 2,
	ErosionSpeed = 3,
    XpMultiplier = 1.0,
    StatsDecrease = 3,
    NatureAbundance = 3,
    Alarm = 4,
    LockedHouses = 6,
    FoodRotSpeed = 3,
    FridgeFactor = 3,
    Farming = 3,
    LootRespawn = 1,
    StarterKit = false,
    Nutrition = true,
    TimeSinceApo = 1,
    PlantResilience = 3,
    PlantAbundance = 3,
    EndRegen = 3,
    
    CarSpawnRate = 3,
    LockedCar = 3,
    CarAlarm = 2,
    ChanceHasGas = 1,
    InitialGas = 2,
    CarGeneralCondition = 1,
    RecentlySurvivorVehicles = 1,
    
    ZombieLore = {
        Speed = 2,
        Strength = 2,
        Toughness = 2,
        Transmission = 1,
        Mortality = 5,
        Reanimate = 3,
        Cognition = 3,
        Memory = 2,
        Decomp = 1,
        Sight = 2,
        Hearing = 2,
        Smell = 2,
        ThumpNoChasing = 1,
    }
}

